name: Python package build and publish

on: push

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sources
          path: dist/*.tar.gz

  build_wheels:
    name: Build and test manylinux wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.1

      - uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: ./wheelhouse/*.whl

  publish_pypi:
    name: Publish sdist and wheels to PyPI
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
